# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml
#

# This version starts a separte job for each platform config
# in order to get around the AppVeyor limit of 60 mins per job.

shallow_clone: true

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

for:
  -
    matrix:
      only:
        - configuration: Debug
          platform: Win32
          image: Visual Studio 2015

    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.9.9\msvc2015
      PLATFORM_ARGUMENT: --32
      CONFIGURATION_ARGUMENT: --debug

  -
    matrix:
      only:
        - configuration: Release
          platform: x64
          image: Visual Studio 2017
    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.9.9\msvc2017_64
      PLATFORM_ARGUMENT: --64
      CONFIGURATION_ARGUMENT: --release

  -
    matrix:
      only:
        - configuration: Debug
          platform: x64
          image: Visual Studio 2019
    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.15.1\msvc2019_64
      PLATFORM_ARGUMENT: --64
      CONFIGURATION_ARGUMENT: --debug

matrix:
  exclude:
    - configuration: Release
      platform: Win32
      image: Visual Studio 2015
    - configuration: Release
      platform: x64
      image: Visual Studio 2015
    - configuration: Debug
      platform: x64
      image: Visual Studio 2015
    - configuration: Release
      platform: Win32
      image: Visual Studio 2017
    - configuration: Debug
      platform: Win32
      image: Visual Studio 2017
    - configuration: Debug
      platform: x64
      image: Visual Studio 2017
    - configuration: Release
      platform: Win32
      image: Visual Studio 2019
    - configuration: Debug
      platform: Win32
      image: Visual Studio 2019
    - configuration: Release
      platform: x64
      image: Visual Studio 2019

branches:
  only:
    - master

init:
  - echo %PLATFORM% %CONFIGURATION%

install:
  # Python
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Qt
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - echo %IMAGE%
  - cmake --version
  - python --version
  - qmake --version
  - git --version
  - pwd
  - ls -a

  # Update external
  - echo Update external sources
  - sh update_external_sources.sh %PLATFORM_ARGUMENT% %CONFIGURATION_ARGUMENT%
  
  - echo Build VulkanTools deps
  - python scripts/update_deps.py --config=%CONFIGURATION% --arch=%PLATFORM%
  - mkdir build
  - cd build
  - cmake -C../helper.cmake ..
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

  - echo Build vkconfig with Qt framework
  - cd ../vkconfig
  - qmake vkconfig.pro
  - nmake

build:
  parallel: true
  verbosity: quiet

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  ctest -j 16 --output-on-failure -C %CONFIGURATION%


deploy: off
