# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml
#

# This version starts a separte job for each platform config
# in order to get around the AppVeyor limit of 60 mins per job.

# build version format
version: "{build}"

# Free accounts have a max of 1, but ask anyway.
max_jobs: 4

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

for:
  -
    matrix:
      only:
        - configuration: Debug
          platform: Win32
          image: Visual Studio 2015

    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.9.9\msvc2015
      PLATFORM_ARGUMENT: --32
      CONFIGURATION_ARGUMENT: --debug
    init:
      - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
      - set CMAKE_ARGS="-G Visual Studio 14 2015"

  -
    matrix:
      only:
        - configuration: Release
          platform: x64
          image: Visual Studio 2017
    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.9.9\msvc2017_64
      PLATFORM_ARGUMENT: --64
      CONFIGURATION_ARGUMENT: --release
    init:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      - set CMAKE_ARGS="-G Visual Studio 15 2017 Win64"

  -
    matrix:
      only:
        - configuration: Debug
          platform: x64
          image: Visual Studio 2019
    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.15.1\msvc2019_64
      PLATFORM_ARGUMENT: --64
      CONFIGURATION_ARGUMENT: --debug
    init:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
      - set CMAKE_ARGS="-G Visual Studio 16 2019 -A x64"

matrix:
  exclude:
    - configuration: Release
      platform: Win32
      image: Visual Studio 2015
    - configuration: Release
      platform: x64
      image: Visual Studio 2015
    - configuration: Debug
      platform: x64
      image: Visual Studio 2015
    - configuration: Release
      platform: Win32
      image: Visual Studio 2017
    - configuration: Debug
      platform: Win32
      image: Visual Studio 2017
    - configuration: Debug
      platform: x64
      image: Visual Studio 2017
    - configuration: Release
      platform: Win32
      image: Visual Studio 2019
    - configuration: Debug
      platform: Win32
      image: Visual Studio 2019
    - configuration: Release
      platform: x64
      image: Visual Studio 2019

branches:
  only:
    - master

install:
  # Python
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Qt
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - echo %IMAGE%
  - cmake --version
  - python --version
  - qmake --version
  - git --version
  - pwd
  - ls -a

  # Update external
  - echo Update external sources
  - update_external_sources.bat %PLATFORM_ARGUMENT% %CONFIGURATION_ARGUMENT%
  
  - echo Build VulkanTools deps
  - python scripts/update_deps.py --config=%CONFIGURATION% --arch=%PLATFORM%
  - mkdir build
  - cd build
  - cmake %CMAKE_ARGS% -C ../helper.cmake ..
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

  - echo Build vkconfig with Qt framework
  # Visual Studio command line https://docs.microsoft.com/fr-fr/cpp/build/building-on-the-command-line?view=msvc-160
  #- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat"
  - cd ../vkconfig
  - qmake vkconfig.pro
  - nmake

build:
  parallel: true
  verbosity: quiet

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  ctest -j 16 --output-on-failure -C %CONFIGURATION%


deploy: off
