# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml
#

# This version starts a separte job for each platform config
# in order to get around the AppVeyor limit of 60 mins per job.

shallow_clone: true

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  PYTHON: "C:\\Python35"

branches:
  only:
    - master

init:
  - echo %PLATFORM% %CONFIGURATION%
  - cmake --version

install:
  # Python
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version

  # Qt
  - if %PLATFORM% == x64 (set QTDIR=C:\Qt\5.9.9\msvc2017_64)
  - if %PLATFORM% == Win32 (set QTDIR=C:\Qt\5.9.9\msvc2017)
  - set PATH=%PATH%;%QTDIR%\bin
  - qmake --version

before_build:
  - if %IMAGE% == "Visual Studio 2015" (set GENERATOR="Visual Studio 14 2015")
  - if %IMAGE% == "Visual Studio 2017" (set GENERATOR="Visual Studio 15 2017")
  - if %IMAGE% == "Visual Studio 2019" (set GENERATOR="Visual Studio 16 2019")
  - echo GENERATOR=%GENERATOR%

  # Update external
  - echo Update external sources
  - if %PLATFORM% == Win32 (if %CONFIGURATION% == Debug (update_external_sources.bat --32 --debug))
  - if %PLATFORM% == Win32 (if %CONFIGURATION% == Release (update_external_sources.bat --32 --release))
  - if %PLATFORM% == x64 (if %CONFIGURATION% == Debug (update_external_sources.bat --64 --debug))
  - if %PLATFORM% == x64 (if %CONFIGURATION% == Release (update_external_sources.bat --64 --release))
  
  - echo Build VulkanTools deps
  - python scripts/update_deps.py --config=%CONFIGURATION% --arch=%PLATFORM%
  - mkdir build
  - cd build
  - cmake -G %GENERATOR% -C../helper.cmake ..
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

  - echo Build vkconfig with Qt framework
  - cd ../vkconfig
  - qmake vkconfig.pro
  - nmake

build:
  parallel: true
  verbosity: quiet

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

# Build only x64 Release and Win32(x86) Debug to reduce build time.
# This should still provide adequate 32-bit vs 64-bit and
# Release vs Debug coverage.
matrix:
  exclude:
    - configuration: Release
      platform: Win32
    - configuration: Debug
      platform: x64

test_script:
  ctest -j 16 --output-on-failure -C %CONFIGURATION%


deploy: off
