# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml
#

# This version starts a separte job for each platform config
# in order to get around the AppVeyor limit of 60 mins per job.

shallow_clone: true

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

for:
  -
    matrix:
      only:
        - configuration: Debug
          platform: Win32
          image: Visual Studio 2015

    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.9.9\msvc2015
      PLATFORM_ARGUMENT: --32
      CONFIGURATION_ARGUMENT: --debug
      GENERATOR: "Visual Studio 14 2015"

  -
    matrix:
      only:
        - configuration: Release
          platform: x64
          image: Visual Studio 2017
    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.9.9\msvc2017_64
      PLATFORM_ARGUMENT: --64
      CONFIGURATION_ARGUMENT: --release
      GENERATOR: "Visual Studio 15 2017 Win64"

  -
    matrix:
      only:
        - configuration: Release
          platform: x64
          image: Visual Studio 2019
    environment:
      PYTHON: C:\Python35
      QTDIR: C:\Qt\5.15.1\msvc2019_64
      PLATFORM_ARGUMENT: --64
      CONFIGURATION_ARGUMENT: --debug
      GENERATOR: "Visual Studio 16 2019 Win64"

# Build only x64 Release and Win32(x86) Debug to reduce build time.
# This should still provide adequate 32-bit vs 64-bit and
# Release vs Debug coverage.
matrix:
  only:
    - configuration: Debug
      platform: Win32
      image: Visual Studio 2015
    - configuration: Release
      platform: x64
      image: Visual Studio 2017
    - configuration: Debug
      platform: x64
      image: Visual Studio 2019

branches:
  only:
    - master

init:
  - echo %IMAGE% %PLATFORM% %CONFIGURATION%

install:
  # Python
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Qt
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - cmake --version
  - python --version
  - qmake --version

  - echo GENERATOR=%GENERATOR%

  # Update external
  - echo Update external sources
  - update_external_sources.bat %PLATFORM_ARGUMENT% %CONFIGURATION_ARGUMENT%
  
  - echo Build VulkanTools deps
  - python scripts/update_deps.py --config=%CONFIGURATION% --arch=%PLATFORM%
  - mkdir build
  - cd build
  - cmake -G %GENERATOR% -C../helper.cmake ..
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

  - echo Build vkconfig with Qt framework
  - cd ../vkconfig
  - qmake vkconfig.pro
  - nmake

build:
  parallel: true
  verbosity: quiet

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  ctest -j 16 --output-on-failure -C %CONFIGURATION%


deploy: off
